### ISSUE TITLE
merged directory

### ISSUE THREAD

**Issue by drippel** [ahnick/dockershare#1]
I have 4 container running on my host system.  5 including dockerhare.

When I execute the docker exec dockershare $CONTAINER command for each container.
No issues or errors from the share.sh.
For example,  docker exec dockershare share httpd

I then mount the shares with
mount -t cifs //0.0.0.0/containers /opt/projects/containers
Again, no issues or errors.

When I cd and ls into the mounted directories.  3 are fine.  I can see the file system of the container as expected.
1 of the mounted shares contains a single directory 'merged'.
If I cd into merged, the only contents is again a single directory named 'merge'.  And it appears to repeat ad nauseum.

I was wondering if you have seen anything like this before.  I have tried deleting all the containers.  And restarting them from the images.  It appears to be consistent.

**Comment by drippel** [comment]
I looks like the issue isn't with dockershare.

Here is a directory listing for the share that is failing

[root@localhost merged]# pwd
/var/lib/docker/overlay/08a5b2089c30d994faf55e4083bd373cb34ad303a901f9116d641b9b6cf558df/merged
[root@localhost merged]# ls -l
total 0
lrwxrwxrwx. 1 root root 88 Aug  9 13:36 merged -> /docker/overlay//08a5b2089c30d994faf55e4083bd373cb34ad303a901f9116d641b9b6cf558df/merged
[root@localhost merged]# 


the merged directory is a link back to itself.

Any ideas on what the fix for this is?

**Comment by ahnick** [comment]
@drippel Sorry, for the delay.  For some reason I missed this issue when you originally posted it.  Did you figure out your issue or are you still experiencing it?  If you are still experiencing it, here are a few thoughts:

- Does the root level itself contain a symlink?
- Are there any volume mounts to that same directory?
- Do you have an example of a docker image that can repeat this problem?

**Comment by ahnick** [comment]
@drippel As I'm not currently able to replicate this issue I'm closing the issue for now.  Please let me know if you have further updates and we can always reopen.
